# Generated by Django 5.1.4 on 2025-03-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=256)),
                ('starting_bid', models.IntegerField()),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
    ]
