# Generated by Django 5.1.4 on 2025-03-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
