# Generated by Django 5.1.4 on 2025-03-03 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlisting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
